### ISSUE TITLE
"Searchdialog" 

### ISSUE THREAD

**Issue by Laern2Do** [ijgnd/anki__BetterSearch_misc#1]
hi there,

I've install bettersearch on anki2.1.22 on window 10, but is not seeing the "searchdialog" option associate with it. please advice. thx!
![image](https://user-images.githubusercontent.com/63658303/86929599-a3768800-c0fb-11ea-85dd-a511adbe35ac.png)

addon and browser
![image](https://user-images.githubusercontent.com/63658303/86929934-07994c00-c0fc-11ea-80e8-ce908fd98004.png)

![image](https://user-images.githubusercontent.com/63658303/86929886-f8b29980-c0fb-11ea-821d-45390aa8af83.png)

(also, is there a shortcut assoiciate with the serachdialog, like ctrl+f for default in browser?)

**Comment by ijgnd** [comment]
I was too optimistic. I just adjusted the description of the side-by-side add-on like this: 

> The button "SearchDialog" is created by a new version of the add-on BetterSearch (which hasn't been uploaded to ankiweb yet).

I have no final release date yet. 

It also might never work with 2.1.22 because .22 might be too old.

**Comment by Laern2Do** [comment]
ah, okie
thx you for the clarification!
